### ISSUE TITLE
How to send a message to many device?

### ISSUE THREAD

**Issue by CoverID** [andrei-m-code/CorePush#63]
How to send a message to multiple devices (token) ~~both iOS and~~ Android like PushSharp library did?

**Comment by andrei-m-code** [comment]
@CoverID what stops you from doing this:

```
var tasks = registrationIds.Select(id => sender.SendAsync(id, payload));
await Task.WhenAll(tasks);

```
This library is meant to be clean and simple. I'd prefer to avoid anything that is not that necessary. Does that help?
